name: 'Build and deploy container on heroku'
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build and push to heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push container into heroku:registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
          # a
        run: |
          heroku container:login
          heroku container:push -a "${APP_NAME}" web
          heroku container:release web -a "${APP_NAME}"
