name: Database population

# Controls when the workflow will run
on:
  # Triggers the workflow in the middle of the week
  schedule:
    - cron: '00 11,15 * * 0-4'

jobs:
  populate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Post request to api
        env:
          URL: "${{ secrets.HEROKU_APP_URL }}api/dolar-history/?count=15"
          API_KEY: ${{ secrets.DOLAR_VISUALIZER_API_KEY }}
        run: curl -d {} "${URL}" -H "Authorization:\ Bearer\ ${API_KEY}"
